use std::{collections::BTreeSet, fmt};

/// Deterministic output produced by a processor transition.
///
/// `Ready` is the protocol core's handoff to an outer shell. It contains
/// ordered output batches and does not perform I/O itself. The shell owns
/// database writes, networking, timers, and runtime execution; the core only
/// describes the protocol-owned work that should happen next.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Ready {
    batches: Vec<ReadyBatch>,
}

impl Ready {
    /// Returns an empty ready output.
    #[must_use]
    pub const fn none() -> Self {
        Self {
            batches: Vec::new(),
        }
    }

    /// Creates ready output from deterministic batches.
    ///
    /// The caller-provided batch order is preserved. Each batch id may appear
    /// at most once in one `Ready` value so a later lifecycle event can
    /// acknowledge a specific hard-output batch without ambiguity.
    ///
    /// # Errors
    ///
    /// Returns [`ReadyError::DuplicateBatch`] when more than one batch has the
    /// same [`ReadyBatchId`].
    pub fn from_batches<I>(batches: I) -> Result<Self, ReadyError>
    where
        I: IntoIterator<Item = ReadyBatch>,
    {
        let mut batch_ids = BTreeSet::new();
        let mut ordered_batches = Vec::new();

        for batch in batches {
            if !batch_ids.insert(batch.id()) {
                return Err(ReadyError::DuplicateBatch { batch: batch.id() });
            }

            ordered_batches.push(batch);
        }

        Ok(Self {
            batches: ordered_batches,
        })
    }

    /// Returns true when the transition produced no ready outputs.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.batches.is_empty()
    }

    /// Returns output batches in deterministic emission order.
    #[must_use]
    pub fn batches(&self) -> &[ReadyBatch] {
        &self.batches
    }
}

/// Stable identity for a ready output batch.
///
/// Batch ids are generated by deterministic core transitions and are later
/// used by lifecycle events to acknowledge completion of hard shell work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ReadyBatchId(u64);

impl ReadyBatchId {
    /// Creates a ready batch identity.
    #[must_use]
    pub const fn new(id: u64) -> Self {
        Self(id)
    }

    /// Returns the underlying deterministic batch value.
    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl fmt::Display for ReadyBatchId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "ready batch {}", self.0)
    }
}

/// One correlatable group of ready outputs.
///
/// A batch is non-empty and keeps output order exactly as supplied by the
/// deterministic transition that created it. When a batch contains hard shell
/// work, the shell can report completion by referencing the batch id.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReadyBatch {
    id: ReadyBatchId,
    outputs: Vec<ReadyOutput>,
}

impl ReadyBatch {
    /// Creates a non-empty ready output batch.
    ///
    /// # Errors
    ///
    /// Returns [`ReadyBatchError::EmptyOutputBatch`] when no outputs are
    /// supplied.
    pub fn new<I>(id: ReadyBatchId, outputs: I) -> Result<Self, ReadyBatchError>
    where
        I: IntoIterator<Item = ReadyOutput>,
    {
        let outputs = outputs.into_iter().collect::<Vec<_>>();

        if outputs.is_empty() {
            return Err(ReadyBatchError::EmptyOutputBatch { batch: id });
        }

        Ok(Self { id, outputs })
    }

    /// Returns the stable batch identity.
    #[must_use]
    pub const fn id(&self) -> ReadyBatchId {
        self.id
    }

    /// Returns outputs in deterministic emission order.
    #[must_use]
    pub fn outputs(&self) -> &[ReadyOutput] {
        &self.outputs
    }
}

/// One protocol-owned action the shell should perform.
///
/// The current output surface models only hard persistence work. Future
/// protocol transitions can add more output variants without moving runtime,
/// network, timer, or storage-engine behavior into the core.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReadyOutput {
    /// Persist the local processor projection before dependent protocol output.
    PersistProcessorState,
}

/// Ready construction errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReadyError {
    /// The same batch id appeared more than once in one ready output.
    DuplicateBatch {
        /// Duplicated ready batch id.
        batch: ReadyBatchId,
    },
}

impl fmt::Display for ReadyError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DuplicateBatch { batch } => {
                write!(formatter, "{batch} appears more than once")
            }
        }
    }
}

impl std::error::Error for ReadyError {}

/// Ready batch construction errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReadyBatchError {
    /// A ready batch was created without any outputs.
    EmptyOutputBatch {
        /// Empty ready batch id.
        batch: ReadyBatchId,
    },
}

impl fmt::Display for ReadyBatchError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyOutputBatch { batch } => {
                write!(formatter, "{batch} does not contain any outputs")
            }
        }
    }
}

impl std::error::Error for ReadyBatchError {}
